---
# yamllint disable rule:line-length

sudo: true

addons:
  apt:
    packages:
      - docker-ce
      - python
      - realpath
      - ruby

env:
  global:
    - CONTAINER_REPO="johnstrunk/fs-performance"

jobs:
  include:
    - name: Linters
      install:
        - travis_retry gem install asciidoctor mdl
        - travis_retry pip install --user yamllint
      script:
        - .travis/pre-commit.sh --require-all
    - name: Build
      script:
        - ./build.sh
      deploy:
        # Master branch will push the container to :latest
        - provider: script
          on:  # yamllint disable-line rule:truthy
            branch: master
          script: .travis/push_container.sh ${CONTAINER_REPO} verbatim latest
        # Tags of the form v + SEMVER (e.g., v1.2.3) will push to the
        # corresponding container version number (e.g., :1.2.3).
        - provider: script
          on:  # yamllint disable-line rule:truthy
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+
          script: .travis/push_container.sh ${CONTAINER_REPO} version "$TRAVIS_TAG"
