---
# This is a job file for kubernetes to run the fs-performance tests
#
# Usage:
# - Modify the PVC to obtain the type of storage you want to test.
#   This includes adjusting the accessModes and storageClass.
# - Apply this file: kubectl apply -f fs-performance.yml
# - When the job is done, read the pod log for the results.
# - Clean up: kubctl delete -f fs-performance.yml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fs-perf-target
spec:
  # To test a particular type of storage, set the name of the StorageClass here.
  # storageClassName: gp2
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: fs-performance
spec:
  template:
    metadata:
      name: fs-performance
    spec:
      containers:
        - name: fs-performance
          image: quay.io/johnstrunk/fs-performance:latest
          # For debugging, uncomment this then exec into the pod...
          # command: ["/bin/bash", "-c", "sleep infinity"]
          env:
            # Override the list of the benchmarks to run (space separated)
            # See functions bench_* in entry.sh for full list
            # - name: BENCHMARKS
            #   value: "clone kernel"
            # TARGET_PATH must match the path for the volumeMount, below.
            - name: TARGET_PATH
              value: "/target"
          volumeMounts:
            - name: target
              mountPath: /target
      restartPolicy: Never
      volumes:
        - name: target
          persistentVolumeClaim:
            claimName: fs-perf-target
