---
# This is a job file for kubernetes to run the fs-performance tests
#
# Usage:
# - Modify the PVC to obtain the type of storage you want to test.
#   This includes adjusting the accessModes and storageClass.
# - Apply this file: kubectl apply -f fs-performance.yml
# - When the job is done, read the pod log for the results.
# - Clean up: kubctl delete -f fs-performance.yml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fs-perf-target
spec:
  # storageClassName: myclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: fs-performance
spec:
  template:
    metadata:
      name: fs-performance
    spec:
      containers:
        - name: fio
          image: quay.io/johnstrunk/fs-performance:latest
          args: ["clone", "fio", "kernel"]
          env:
            - name: TARGET_CAPACITY_MB
              value: "500"
            - name: TARGET_PATH
              value: "/target"
            - name: CLONE_REPO
              value: "https://github.com/gluster/glusterfs.git"
          volumeMounts:
            - name: target
              mountPath: /target
      restartPolicy: Never
      volumes:
        - name: target
          persistentVolumeClaim:
            claimName: fs-perf-target
